[package]
name = "git-peak"
version = "0.1.0"
description = "A little utility to navigate Git branches, quickly switch between them, and when you're done with them, delete them."
authors = ["Tom de Bruijn <tom@tomdebruijn.com>"]
license = "MIT"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
ratatui = "0.29.0"
color-eyre = "0.6.3"
git2 = "0.20.2"
chrono = { version = "0.4", features = ["clock"] }

[[bin]]
name = "peak"
path = "src/main.rs"
